name: ML Pipeline CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8 (optional)
      run: |
        # Install flake8 if you want linting
        # pip install flake8
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        echo "Linting skipped - add flake8 if needed"
    
    - name: Test data loading
      run: |
        python -c "
        import pandas as pd
        import numpy as np
        print('Testing basic imports...')
        print('✅ Core libraries imported successfully')
        "
    
    - name: Validate project structure
      run: |
        echo "Checking project structure..."
        ls -la
        echo "✅ Project structure validated"
